# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  timeout: 5000


development:
  <<: *default
  username: vladislavshved
  host: localhost
  database: dashboards_dev

test:
  <<: *default
  username: vladislavshved
  host: localhost
  database: dashboards_test

production:
  <<: *default
  database: dashboards_production
